---
- name: ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip.install
    state: latest
    allow_prerelease: no

- name: ensure Firefox is installed via Chocolatey
  win_chocolatey:
    name: firefox
    state: latest
    allow_prerelease: no
