---
- name: Run powershell script
  script: ../../../scripts/bootstrap_win_10/pre-reqs.ps1

- name: "Check for existing boxstarter install."
  win_stat:
    path: "{{ boxstarter_path }}/boxstarter.bat"
  register: boxstarter_bat

- name: "Check for existing chocolatey install."
  win_stat:
    path: "{{ chocolatey_path }}/choco.exe"
  register: chocolatey_exe

- debug:
    var: chocolatey_exe
    verbosity: 1

- debug:
    var: boxstarter_bat
    verbosity: 1

- name: "Install Boxstarter(installs Chocolatey too)"
  raw: "iex ((New-Object System.Net.WebClient).DownloadString('{{ boxstarter_installer }}')); get-boxstarter -Force"
  when:
    - boxstarter_bat.stat.exists is defined
    - not boxstarter_bat.stat.exists
    - chocolatey_exe.stat.exists is defined
    - not chocolatey_exe.stat.exists

- name: ensure latest powershell is installed via Chocolatey
  win_chocolatey:
    name: powershell
    state: latest
    allow_prerelease: no

- name: ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip.install
    state: latest
    allow_prerelease: no
