---
- include: apt.yml
- include: limits.yml

- name: "Run an upgrade"
  apt:
    update_cache: yes
    upgrade: yes

- name: "Add common packages"
  apt: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - autoconf
    - bison
    - build-essential
    - ca-certificates
    - conntrack
    - curl
    - dkms
    - dnsutils
    - dos2unix
    - fontconfig
    - fonts-firacode
    - fortune
    - git-core
    - git-extras
    - git-lfs
    - gnupg
    - html2text
    - jq
    - libcurl4-openssl-dev
    - libffi-dev
    - libncurses5-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - locate
    - lsb-release
    - lynx
    - net-tools
    - nmap
    - nmon
    - nodejs
    - openntpd
    - openssl
    - pandoc
    - parted
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - rsync
    - sed
    - snmp
    - sof
    - ssh
    - software-properties-common
    - speedtest-cli
    - sqlite
    - sshpass
    - sysstat
    - time
    - tmux
    - unzip
    - yadm
    - zip
    - zlib1g-dev
