# defaults file for postfix
---
postfix_install:
  - postfix
  - mailutils
  - libsasl2-2
  - sasl2-bin
  - libsasl2-modules
postfix_hostname: "{{ ansible_fqdn }}"
postfix_mailname: "{{ ansible_fqdn }}"
postfix_aliases: []
postfix_virtual_aliases: []
postfix_sender_canonical_maps: []
postfix_generic: []
postfix_relayhost: true
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: true
postfix_sasl_user: "{{ lookup('credstash', 'postfix.user', region='us-east-1') }}"
postfix_sasl_password: "{{ lookup('credstash', 'postfix.pw', region='us-east-1') }}"
postfix_sasl_security_options: noanonymous
postfix_sasl_mechanism_filter: ''
postfix_inet_interfaces: all
postfix_inet_protocols: all
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain
postfix_mynetworks:
  - "{{ lookup('credstash', 'enterprise.net', region='us-east-1') }}"
  - "{{ lookup('credstash', 'servers.net', region='us-east-1') }}"
  - 127.0.0.0/8
  - '[::ffff:127.0.0.0]/104'
  - '[::1]/128'
postfix_smtpd_banner: '$myhostname ESMTP $mail_name'
postfix_disable_vrfy_command: false
postfix_message_size_limit: 10240000
